export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header style={{backgroundColor: "lightblue", padding: "12px"}}>
          Header
        </header>

        {children} {/* This is where the child components will be rendered */}

        <footer style={{backgroundColor: "ghostwhite", padding: "12px"}}>
          Footer
        </footer>
        </body>
    </html>
  )
}
